page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'books'
    template: 'book'
    name: 'title'
    dir: 'books-i-have-not-read'
    filter_condition: "record['did-i']['read'] == false"

  - data: 'books'
    template: 'book'
    name: 'title'
    dir: 'books-by-orwell'
    filter_condition: "record['author'] == 'George Orwell'"
    
